import Head from "next/head";
import {Inter} from "next/font/google";
import styles from "@/styles/Home.module.css";
import {useEffect, useState} from "react";

const inter = Inter({subsets: ["latin"]});

export default function Characters() {
    const [characters, setCharacters] = useState<null | Array<CharactersType>>(null)

    useEffect(() => {
        const fetchData = async () => {
            try {
                const response = await fetch("URL_ВАШЕГО_API");
                const data = await response.json();
                setCharacters(data);
            } catch (error) {
                console.error("Ошибка при получении данных:", error);
            }
        };

        fetchData();
    }, []);

    return (
        <>
            <Head>
                <title>Characters</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                {characters && characters.map(characters => (
                    <>
                        <div>{characters.name}</div>
                    </>
                ))}
            </main>
        </>
    );
}


//types

type CharactersType = {
    id: number
    name: string
}